# Generated by Django 6.0 on 2026-01-04 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='monthvariableexpense',
            new_name='budgeting_m_month_c_44c6b4_idx',
            old_name='budgeting_m_month_ca_676d07_idx',
        ),
        migrations.AddField(
            model_name='monthrecurringexpense',
            name='month_budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budgeting.monthbudget'),
        ),
    ]
