# Generated by Django 6.0 on 2026-01-06 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0002_rename_budgeting_m_month_ca_676d07_idx_budgeting_m_month_c_44c6b4_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_type', models.CharField(choices=[('recurring', 'Recurring'), ('variable', 'Variable')], default='recurring', max_length=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('month_budget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budgeting.monthbudget')),
                ('month_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgeting.monthcategory')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budgeting.recurringexpensetemplate')),
            ],
            options={
                'ordering': ['month_category__sort_order', 'expense_type', 'name'],
            },
        ),
    ]
