# Generated by Django 6.0 on 2026-01-06 19:49

from django.db import migrations


def move_data(apps, schema_editor):
    MonthRecurringExpense = apps.get_model('budgeting', 'MonthRecurringExpense')
    MonthVariableExpense = apps.get_model('budgeting', 'MonthVariableExpense')
    MonthExpense = apps.get_model('budgeting', 'MonthExpense')

    for re in MonthRecurringExpense.objects.all():
        MonthExpense.objects.create(
            month_budget=re.month_budget,
            month_category=re.month_category,
            name=re.name,
            amount=re.amount,
            expense_type='recurring',
            notes=re.notes,
            enabled=re.enabled,
            template=re.template
        )

    for ve in MonthVariableExpense.objects.all():
        MonthExpense.objects.create(
            month_budget=ve.month_category.month_budget,
            month_category=ve.month_category,
            name=ve.name,
            amount=ve.amount,
            expense_type='variable',
            date=ve.date,
            notes=ve.notes,
            enabled=True
        )


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0003_monthexpense'),
    ]

    operations = [
        migrations.RunPython(move_data),
    ]
