# Generated by Django 6.0 on 2026-01-06 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0004_auto_20260106_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthrecurringexpense',
            name='month_budget',
        ),
        migrations.RemoveField(
            model_name='monthrecurringexpense',
            name='month_category',
        ),
        migrations.RemoveField(
            model_name='monthrecurringexpense',
            name='template',
        ),
        migrations.RemoveIndex(
            model_name='monthvariableexpense',
            name='budgeting_m_month_c_44c6b4_idx',
        ),
        migrations.DeleteModel(
            name='MonthRecurringExpense',
        ),
        migrations.DeleteModel(
            name='MonthVariableExpense',
        ),
    ]
